version: '2'
networks:
    cluster:
        driver: bridge

volumes:
    cluster-archives:
        driver: local

services:
    pgmaster:
        image: tiagoor/postgresql-cluster-pgsql
#        build:
#            context: .
#            dockerfile: Pgsql.Dockerfile
        volumes:
            - "cluster-archives:/var/cluster_archive"
        environment:

            INITIAL_NODE_TYPE: master # Used by `repmgr register` as initial node role
                                      # Role can be changed on failover or in live cycle of cluster
                                      # (default: standby, available: master|standby)
            NODE_ID: 1 # Integer number of node
            NODE_NAME: node1 # Node name
            CLUSTER_NODE_NETWORK_NAME: pgmaster # (default: hostanme of the node)

            #database we want to use for application
            POSTGRES_PASSWORD: monkey_pass
            POSTGRES_USER: monkey_vser
            POSTGRES_DB: monkey_db

            CONFIGS: "listen_addresses:'*'"
                                  # in format variable1:value1[,variable2:value2[,...]]
                                  # used for pgpool.conf file



            #defaults:
            CLUSTER_NODE_REGISTER_DELAY: 5 # default is 5
            REPLICATION_DAEMON_START_DELAY: 30 # default is 30
            #REPLICATION_STANDBY_START_DELAY: 20 # unapplicable for master but on standby should be more then CLUSTER_NODE_REGISTER_DELAY
            CLUSTER_NAME: pg_cluster # default is pg_cluster
            REPLICATION_DB: replication_db # default is replication_db
            REPLICATION_USER: replication_user # default is replication_user
            REPLICATION_PASSWORD: replication_pass # default is replication_pass
        ports:
            - 5432:5432
        networks:
            cluster:
                aliases:
                    - pgmaster
#<<< Branch 1
    pgslave1:
        image: tiagoor/postgresql-cluster-pgsql
#        build:
#            context: .
#            dockerfile: Pgsql.Dockerfile
        depends_on:
            - pgmaster
        volumes:
            - "cluster-archives:/var/cluster_archive"
        environment:
            REPLICATION_PRIMARY_HOST: pgmaster
            NODE_ID: 2
            NODE_NAME: node2
            CLUSTER_NODE_NETWORK_NAME: pgslave1 # (default: hostanme of the node)
            REPLICATION_UPSTREAM_NODE_ID: 1
        ports:
            - 5441:5432
        networks:
            cluster:
                aliases:
                    - pgslave1

    # Add more slaves if required
    pgslave2:
        image: tiagoor/postgresql-cluster-pgsql
#        build:
#            context: .
#            dockerfile: Pgsql.Dockerfile
        depends_on:
            - pgslave1
        volumes:
            - "cluster-archives:/var/cluster_archive"
        environment:
            REPLICATION_PRIMARY_HOST: pgslave1 # I want to have cascade Streeming replication
            NODE_ID: 3
            NODE_NAME: node3
            CLUSTER_NODE_NETWORK_NAME: pgslave2 # (default: hostanme of the node)
            REPLICATION_UPSTREAM_NODE_ID: 2
            REPLICATION_STANDBY_START_DELAY: 40 # default: 20
        ports:
            - 5442:5432
        networks:
            cluster:
                aliases:
                    - pgslave2
#>>> Branch 1
#<<< Branch 2
    pgslave3:
        image: tiagoor/postgresql-cluster-pgsql
#        build:
#            context: .
#            dockerfile: Pgsql.Dockerfile
        depends_on:
            - pgmaster
        volumes:
            - "cluster-archives:/var/cluster_archive"
        environment:
            REPLICATION_PRIMARY_HOST: pgmaster
            NODE_ID: 4
            NODE_NAME: node4
            CLUSTER_NODE_NETWORK_NAME: pgslave3 # (default: hostanme of the node)
            REPLICATION_UPSTREAM_NODE_ID: 1
        ports:
            - 5443:5432
        networks:
            cluster:
                aliases:
                    - pgslave3

    pgslave4:
        image: tiagoor/postgresql-cluster-pgsql
#        build:
#            context: .
#            dockerfile: Pgsql.Dockerfile
        depends_on:
            - pgslave3
        volumes:
            - "cluster-archives:/var/cluster_archive"
        environment:
            REPLICATION_PRIMARY_HOST: pgslave3
            NODE_ID: 5
            NODE_NAME: node5
            CLUSTER_NODE_NETWORK_NAME: pgslave4 # (default: hostanme of the node)
            REPLICATION_UPSTREAM_NODE_ID: 4
            REPLICATION_STANDBY_START_DELAY: 40 # default is 20
        ports:
            - 5444:5432
        networks:
            cluster:
                aliases:
                    - pgslave4
#>>> Branch 2
    pgpool:
        image: tiagoor/postgresql-cluster-pgpool
#        build:
#            context: .
#            dockerfile: Pgpool.Dockerfile
        depends_on:
            - pgmaster
            - pgslave1
            - pgslave2
        environment:
            PCP_USER: pcp_user
            PCP_PASSWORD: pcp_pass
            PGPOOL_START_DELAY: 120

            REPLICATION_USER: replication_user
            REPLICATION_PASSWORD: replication_pass

            DB_USERS: monkey_user:monkey_pass # in format user:password[,user:password[...]]
            BACKENDS: "0:pgmaster:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:pgslave1::::,2:pgslave2::::,3:pgslave3::::"
                      # in format num:host:port:weight:data_directory:flag[,...]
                      # defaults:
                      #   port: 5432
                      #   weight: 1
                      #   data_directory: /var/lib/postgresql/data
                      #   flag: ALLOW_TO_FAILOVER
            CONFIGS: "num_init_children:250,max_pool:4,search_primary_node_timeout:5"
                      # in format variable1:value1[,variable2:value2[,...]]
                      # used for pgpool.conf file
        ports:
            - 5430:5432
            - 9898:9898 # PCP
        networks:
            cluster:
                aliases:
                    - pgpool
